Komorebic(args) => RunWait("komorebic.exe " args, , "Hide")

; Restart
Komorebic("stop")
RunWait("taskkill /im komorebi.exe")
Komorebic("start -c " HomeDir "\.config\komorebi\komorebi.json")

; Config
Komorebic("focus-follows-mouse enable -i windows")

; Komorebic("toggle-window-tiling-behaviour")
; Komorebic("remove-title-bar exe explorer.exe")
; Komorebic("remove-title-bar exe alacritty.exe")
; Komorebic("remove-title-bar exe obsidian.exe")

; Keyboard
#w::Komorebic("close")
#Enter:: Komorebic("promote")
#+Enter:: Komorebic("unstack")
#t:: Komorebic("toggle-float")
#+t:: Komorebic("toggle-title-bars")
#+f:: Komorebic("toggle-monocle")
#+r:: Komorebic("retile")
#p:: Komorebic("toggle-pause")
#+[:: Komorebic("cycle-focus previous")
#+]:: Komorebic("cycle-focus next")
#[:: Komorebic("cycle-stack previous")
#]:: Komorebic("cycle-stack next")
#Tab:: Komorebic("cycle-workspace next")
#+Tab:: Komorebic("cycle-workspace previous")
#CapsLock:: Komorebic("cycle-monitor next")
#+CapsLock:: Komorebic("cycle-monitor previous")
#h:: Komorebic("focus left")
#j:: Komorebic("focus down")
#k:: Komorebic("focus up")
#l:: Komorebic("focus right")
#+h:: Komorebic("move left")
#+j:: Komorebic("move down")
#+k:: Komorebic("move up")
#+l:: Komorebic("move right")
#^h:: Komorebic("stack left")
#^j:: Komorebic("stack down")
#^k:: Komorebic("stack up")
#^l:: Komorebic("stack right")
#x:: Komorebic("flip-layout horizontal")
#y:: Komorebic("flip-layout vertical")
#=:: Komorebic("resize-axis horizontal increase")
#-:: Komorebic("resize-axis horizontal decrease")
#+=:: Komorebic("resize-axis vertical increase")
#+-:: Komorebic("resize-axis vertical decrease")
#1:: Komorebic("focus-workspace 0")
#2:: Komorebic("focus-workspace 1")
#3:: Komorebic("focus-workspace 2")
#4:: Komorebic("focus-workspace 3")
#+1:: Komorebic("send-to-workspace 0")
#+2:: Komorebic("send-to-workspace 1")
#+3:: Komorebic("send-to-workspace 2")
#+4:: Komorebic("send-to-workspace 3")

; Mouse
F13:: Komorebic("cycle-workspace next")
F14:: Komorebic("cycle-workspace previous")
F15:: Komorebic("cycle-move-to-workspace next")
F16:: Komorebic("cycle-move-to-workspace previous")
F17:: Komorebic("toggle-monocle")
F18:: Komorebic("toggle-pause")
F19:: Komorebic("cycle-stack next")
F20:: Komorebic("cycle-stack previous")