primary_light: &primary_light "#FFFFFFFF"
background_light: &background_light "#FFFFFF55"
background_dark: &background_dark "transparent"
workspace_symbol: &workspace_symbol " "

gaps:
  inner_gap: 3
  outer_gap: 0

focus_borders:
  active:
    enabled: true
    color: "#e0af68"
  inactive:
    enabled: true
    color: "#937344"

general:
  show_floating_on_top: false
  floating_window_move_amount: "6%"
  toggle_workspace_on_refocus: false
  focus_follows_cursor: false
  cursor_follows_focus: false

bar:
  height: "30"
  position: "top"
  background: "transparent"
  foreground: *primary_light
  #font_family: "Segoe UI"
  font_family: "CaskaydiaCove Nerd Font"
  #font_family: "CodeNewRoman Nerd Font"
  #font_family:  "Iosevka Nerd Font"
  padding: 0
  margin: 0
  offset_x: 0
  offset_y: 0
  border_radius: 0
  border_width: 0
  border_color: "transparent"

  components_center:
    - type: "workspaces"
      background: "transparent"
      border_width: 0
      padding: 0
      margin: 0
      offset_x: 0
      offset_y: 0

      focused_workspace_foreground: *primary_light
      focused_workspace_background: *background_dark
      focused_workspace_border_color: *background_dark

      default_workspace_foreground: *background_light
      default_workspace_background: *background_dark
      default_workspace_border_color: *background_dark

      displayed_workspace_foreground: *background_light
      displayed_workspace_background: *background_dark
      displayed_workspace_border_color: *background_dark

      # components_left:
      #- type: "system tray"
      #  margin: "5 0 5 0"
      # label_expand_text: " "
      #  label_collapse_text: " "
  components_right:
    - type: "clock"
      font_family: "Iosevka Nerd Font"
      font_size: "15px"
      font_weight: "800"
      foreground: *primary_light
      margin: "0 10 0 0"
      time_formatting: "ddd dd/MM/yy   HH:mm"
  #   - type: "binding mode"
  #     foreground: *background_dark
  #     background: *primary_light
  #     margin: "0 4px 0 0"
  #     padding: "0 8px"
  #   - type: "tiling direction"
  #     # label_horizontal: "  "
  #     # label_vertical: " "
  #     label_horizontal: "<attr fg='#f068f2'>  </attr>"
  #     label_vertical: "<attr fg='#67f0e2'>  </attr>"
  #     background: *background_dark
  #     margin: "0 0px"
  #     padding: "0 8px"
  # components_right:
  #   - type: "image"
  #     source: "C:\\Folder\\AnotherFolder\\image.png"
  # components_left:
  #   - type: "image"
  #     source: "C:\\Folder\\AnotherFolder\\image.png"

workspaces:
  - name: "m0w0"
    display_name: *workspace_symbol
    bind_to_monitor: 1
    keep_alive: true
  - name: "m0w1"
    display_name: *workspace_symbol
    bind_to_monitor: 1
    keep_alive: true
  - name: "m0w2"
    display_name: *workspace_symbol
    bind_to_monitor: 1
    keep_alive: true
  - name: "m0w3"
    display_name: *workspace_symbol
    bind_to_monitor: 1
    keep_alive: true
  - name: "m0w4"
    display_name: *workspace_symbol
    bind_to_monitor: 1
    keep_alive: true

  - name: "m1w0"
    display_name: *workspace_symbol
    bind_to_monitor: 2
    keep_alive: true
  - name: "m1w1"
    display_name: *workspace_symbol
    bind_to_monitor: 2
    keep_alive: true
  - name: "m1w2"
    display_name: *workspace_symbol
    bind_to_monitor: 2
    keep_alive: true
  - name: "m1w3"
    display_name: *workspace_symbol
    bind_to_monitor: 2
    keep_alive: true
  - name: "m1w4"
    display_name: *workspace_symbol
    bind_to_monitor: 2
    keep_alive: true

window_rules:
  - command: "ignore"
    match_process_name: "RoundedTB"
  - command: "ignore"
    match_process_name: "LeagueOfLegends"
  - command: "ignore"
    match_process_name: "League Of Legends"
  - command: "ignore"
    match_class_name: "RiotWindowClass"
  - command: "ignore"
    match_process_name: "LeagueClient"
  - command: "ignore"
    match_process_name: "bg3_dx11"
  - command: "ignore"
    match_process_name: "RotMG Exalt"

  - command: "set floating"
    match_class_name: "#32770" # system dialogs as floating

  - command: "set floating"
    match_process_name: "1Password"

  - command: "set floating"
    match_process_name: "FluentSearch"
    # match_title: "Fluent Search - Settings"

  - command: "set floating"
    match_process_name: "KeyboardSplitter"

  - command: "set floating"
    match_process_name: "LariLauncher"

  - command: "set floating"
    match_process_name: "copyq"

  - command: "set floating"
    match_process_name: "Unity Hub"

  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steamwebhelper"

  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

  - command: "resize borders 0 -2px 0px -2px"
    match_process_name: "firefox"

  - command: "resize borders 0 -2px 0px -2px"
    match_process_name: "librewolf"

  - command: "move to workspace m0w1"
    match_process_name: "rider64"
  - command: "set floating"
    match_class_name: "SunAwtDialog"

  - command: "move to workspace m0w0"
    match_process_name: "Unity"

  - command: "move to workspace m0w2"
    match_process_name: "VSCodium"
    match_class_name: "Chrome_WidgetWin_1"

  - commands: ["move to workspace m1w0", "move left"]
    match_process_name: "Discord"
  - commands:
      [
        "move to workspace m1w0",
        "resize borders 0px 1px 1px 1px",
        "move left",
        "set width 66%",
      ]
    match_process_name: "Vesktop"
  - commands:
      [
        "move to workspace m1w0",
        "resize borders 0px 1px 1px 1px",
        "move left",
        "set width 66%",
      ]
    match_process_name: "ArmCord"

  - commands: ["resize borders 0", "move to workspace m1w0"]
    match_process_name: "Obsidian"

  - command: "move to workspace m1w1"
    match_process_name: "plastic"
  - command: "move to workspace m0w4"
    match_process_name: "plastic"
    match_title: "/(?!^Workspace.*)(^.*$)/"

  - commands: ["move to workspace m1w2", "tiling direction vertical", "move up"]
    match_process_name: "Spark Desktop"
    match_class_name: "Chrome_WidgetWin_1"

  - commands:
      ["move to workspace m1w2", "tiling direction vertical", "move down"]
    match_process_name: "Beeper"

  - command: "move to workspace m1w3"
    match_process_name: "firefox"

  - command: "move to workspace m1w3"
    match_process_name: "vivaldi"
    match_title: ".* - Vivaldi"
  - command: "resize borders 0px -6px -6px -6px"
    match_process_name: "vivaldi"
    match_title: ".* - Vivaldi"
  - command: "move to workspace m1w0"
    match_process_name: "vivaldi"
    match_title: "ClickUp.*"
  - command: "move to workspace m1w4"
    match_process_name: "vivaldi"
    match_title: "YouTube Music.*"
  - command: "move to workspace m1w4"
    match_process_name: "vivaldi"
    match_title: "Twilight Wars.*"

  - command: "ignore"
    match_process_name: "Glorious Companions"
#  - command: "ignore"
#    match_process_name: "Vintagestory"

binding_modes:
  - name: "send"
    keybindings:
      - commands: ["binding mode none", "move left"]
        binding: "NumPad4"
      - commands: ["binding mode none", "move down"]
        binding: "NumPad2"
      - commands: ["binding mode none", "move up"]
        binding: "NumPad8"
      - commands: ["binding mode none", "move right"]
        binding: "NumPad6"

      - commands: ["binding mode none", "move to workspace m0w0"]
        binding: "F18"
      - commands: ["binding mode none", "move to workspace m0w1"]
        binding: "F19"
      - commands: ["binding mode none", "move to workspace m0w2"]
        binding: "F20"
      - commands: ["binding mode none", "move to workspace m0w3"]
        binding: "F21"
      - commands: ["binding mode none", "move to workspace m0w4"]
        binding: "Decimal"

      - commands: ["binding mode none", "move to workspace m1w0"]
        binding: "F13"
      - commands: ["binding mode none", "move to workspace m1w1"]
        binding: "F14"
      - commands: ["binding mode none", "move to workspace m1w2"]
        binding: "F15"
      - commands: ["binding mode none", "move to workspace m1w3"]
        binding: "F16"
      - commands: ["binding mode none", "move to workspace m1w4"]
        binding: "F17"

      - command: "binding mode none"
        binding: "Escape"

keybindings:
  - command: "tiling direction toggle"
    binding: "Divide"
  - command: "binding mode send"
    binding: "Multiply"
  - command: "close"
    binding: "NumPad5"
  - command: "toggle maximized"
    binding: "F24"
  - command: "focus mode toggle"
    binding: "NumPad0"
  - command: "exit wm"
    binding: "Subtract"
  - command: "reload config"
    binding: "Add"
  - command: "focus workspace next"
    binding: "F22"
  - command: "focus workspace prev"
    binding: "F23"
  # - command: "toggle floating"
  #   binding: "Alt+Shift+T"
  # - command: "set minimized"
  #   binding: "Alt+Shift+X"

  - command: "resize width +10%"
    binding: "NumPad1"
  - command: "resize width -10%"
    binding: "NumPad3"
  - command: "resize height +10%"
    binding: "NumPad7"
  - command: "resize height -10%"
    binding: "NumPad9"

  - command: "focus left"
    binding: "NumPad4"
  - command: "focus down"
    binding: "NumPad2"
  - command: "focus up"
    binding: "NumPad8"
  - command: "focus right"
    binding: "NumPad6"

  - command: "focus workspace m1w0"
    binding: "F13"
  - command: "focus workspace m1w1"
    binding: "F14"
  - command: "focus workspace m1w2"
    binding: "F15"
  - command: "focus workspace m1w3"
    binding: "F16"
  - command: "focus workspace m1w4"
    binding: "F17"

  - command: "focus workspace m0w0"
    binding: "F18"
  - command: "focus workspace m0w1"
    binding: "F19"
  - command: "focus workspace m0w2"
    binding: "F20"
  - command: "focus workspace m0w3"
    binding: "F21"
  - command: "focus workspace m0w4"
    binding: "Decimal"